export const Users = [
  {
    id: 1,
    profilePicture: "person/1.jpg",
    username: "Vibha Mishra",
  },
  {
    id: 2,
    profilePicture: "person/2.jpg",
    username: "Janell Shrum",
  },
  {
    id: 3,
    profilePicture: "person/3.jpg",
    username: "Vaibhav Mishra",
  },
  {
    id: 4,
    profilePicture: "person/4.jpg",
    username: "Dora Hawks",
  },
  {
    id: 5,
    profilePicture: "person/5.jpg",
    username: "Aman Rohila",
  },
  {
    id: 6,
    profilePicture: "person/6.jpg",
    username: "Shivani Jaiswal",
  },
  {
    id: 7,
    profilePicture: "person/7.jpg",
    username: "Travis Bennett",
  },
  {
    id: 8,
    profilePicture: "person/8.jpg",
    username: "Kristen Thomas",
  },
  {
    id: 9,
    profilePicture: "person/9.jpg",
    username: "Akash Awasthi",
  },
  {
    id: 10,
    profilePicture: "person/10.jpg",
    username: "Shruti Shukla",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "posts/2.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,

    photo: "posts/person/1.jpg",
    date: "5 hours ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 3,

    photo: "posts/12.jpg",
    date: "45 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 4,

    photo: "posts/17.jpg",
    date: "55 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 5,
    photo: "posts/9.jpg",
    date: "15 hours ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 6,
    desc: "Every moment is a fresh beginning.",
    photo: "posts/18.jpg",
    date: "10 min ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 7,
    desc: "Sports is Love.",
    photo: "posts/23.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 8,

    photo: "posts/person/3.jpg",
    date: "1 day ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 9,
    photo: "posts/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 10,
    photo: "posts/22.png",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 11,
    photo: "posts/23.jpg",
    date: "3 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 12,
    photo: "posts/person/5.jpg",
    date: "3 mins ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 13,
    photo: "posts/15.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 14,
    photo: "posts/21.jpg",
    date: "2 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 15,
    photo: "posts/person/6.jpg",
    date: "3 days ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 16,
    desc: "Never regret anything that made you smile.",
    photo: "posts/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 17,
    photo: "posts/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 18,

    photo: "posts/19.jpg",
    date: "30 mins ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 19,
    desc: "Change the world by being yourself.",
    photo: "posts/person/9.jpg",
    date: "7 hours ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 20,
    desc: "Change the world by being yourself.",
    photo: "posts/11.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 21,
    photo: "posts/20.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
  {
    id: 22,
    photo: "posts/person/10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
  {
    id: 23,
    photo: "posts/1.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
